[package]
name = "rustket"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustket"
path = "src/lib.rs"

[[bin]]
name = "rustket-bin"
path = "src/main.rs"

[build-dependencies]
bindgen = "0.59.2"
cc = { version = "1.0", features = ["parallel"] }
